### ISSUE TITLE
placing construction sites for extensions needs to check for other structures

### ISSUE THREAD

**Issue by bluecereal** [yeliknewo/kh-screeps#1]
there are no checks done for the container construction site that was generated in config2, or any other possible structures that might be in the way.
https://github.com/yeliknewo/kh-screeps/blob/master/config.js#L152

**Comment by bluecereal** [comment]
untested fix [b3f5e3a6c89581e0ad5599fcc354c1aa7e658f33](https://github.com/yeliknewo/kh-screeps/commit/b3f5e3a6c89581e0ad5599fcc354c1aa7e658f33)

**Comment by yeliknewo** [comment]
If we surround the source with extensions we can't mine as effectively with low work creeps.

**Comment by bluecereal** [comment]
Ok, maybe the source-extensions should be placed at a later level when we have one creep per source (lvl 3?).  In the meantime, where should structures be placed?  We could generate a path and build along it, idk what else.  Build them in a square somewhere near the spawn?

**Comment by bluecereal** [comment]
I like the idea of a 3-tile wide road from the spawn to the controller, where you build along the edges of the highway.

**Comment by yeliknewo** [comment]
the structures should be placed like 2 tiles away from the source in a way that doesn't block movement. The road doesn't need to be 3 wide because it already makes sure there is enough road over time.

**Comment by bluecereal** [comment]
[9407787df77e892802c11cf318e5c4796bf54edc](https://github.com/yeliknewo/kh-screeps/commit/9407787df77e892802c11cf318e5c4796bf54edc)

**Comment by bluecereal** [comment]
It scans a 3x3 space on each side of the spawn, checks if its empty, then generates the construction sites.  Methinks we'll need to be careful of queuing multiple sites for the same tile in the future.

**Comment by yeliknewo** [comment]
they don't need to be near the spawn, they need to be near the source
