### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by bluecereal** [yeliknewo/kh-screeps#17]
Some form of logging might be useful.  For example, you could track the "events" of some new feature you've added, to see if its working, without having to watch the script run over a long period of time.  The AI could also make decisions based on previous happenings its logged.

**Comment by yeliknewo** [comment]
I mean screeps has built in logging we just need to start using it

**Comment by bluecereal** [comment]
!! show me the logging?

**Comment by yeliknewo** [comment]
console.log
