### ISSUE TITLE
Road constructions are being generated too often. 

### ISSUE THREAD

**Issue by bluecereal** [yeliknewo/kh-screeps#2]
This makes it so the extension sites don't get placed, and sometimes the container sites near the sources don't get  spawned either (gets blocked by preexisting road).

**Comment by yeliknewo** [comment]
roads don't block them and they come out of the queue the order they go in

**Comment by bluecereal** [comment]
My creeps didnt have enough time to get through the queue before it was regenerated again.

**Comment by yeliknewo** [comment]
Why would that matter? its not going to build the roads again.

**Comment by bluecereal** [comment]
[2615279148e91901422eb755d64fdbe46da04a85](https://github.com/yeliknewo/kh-screeps/commit/2615279148e91901422eb755d64fdbe46da04a85)

**Comment by yeliknewo** [comment]
The roads won't be built if they aren't finished by controller level 2 tho

**Comment by bluecereal** [comment]
reverted.  config3 wont generate new roads.

**Comment by yeliknewo** [comment]
you don't need to stop generating roads, they will be generated as needed automatically.
