### ISSUE TITLE
merging targetpool2

### ISSUE THREAD

**Issue by bluecereal** [yeliknewo/kh-screeps#3]
I changed over the needTarget params in [job.js](https://github.com/yeliknewo/kh-screeps/blob/targetPool2/src/job.js) to use targetPoolConstants.  I didn't know how to get the new finders to run in targetPool (the ones made with makeFinder). I've not seen it done this way, so I didn't understand.  Hoping you could explain, specifically what the params do in this function signature:
```
function makeFinder(temp_id, temp_interval, temp_offset, temp_func)
```

actually this might be stupid

**Comment by yeliknewo** [comment]
id, number of ticks between calls, offset to the number of ticks between calls, the function

**Comment by bluecereal** [comment]
I should have just looked at the object it was returning.

**Comment by bluecereal** [comment]
I got the targetpool working in [1a7466e79257e71e116ffc39d64193f9a5f5d39f](https://github.com/yeliknewo/kh-screeps/commit/1a7466e79257e71e116ffc39d64193f9a5f5d39f) but not the way we want.  It just calls the finder functions in order from an object instead of using intervals and stuff.  Wasn't sure how to implement that.  I'm fine with this code; a finderSkip could be inserted however many times into the finders obj if necessary.

**Comment by yeliknewo** [comment]
(Game.time + offset) % interval == 0 then run function

**Comment by yeliknewo** [comment]
merged
