### ISSUE TITLE
Target Pool needs to be updated as jobs are finished

### ISSUE THREAD

**Issue by yeliknewo** [yeliknewo/kh-screeps#5]

**Comment by bluecereal** [comment]
When is a job finished?

**Comment by yeliknewo** [comment]
depends on the job. construction jobs are finished when its built, repair jobs are finished when its repaired

**Comment by bluecereal** [comment]
ok.  the code for this could be added to or alongside creep.needTarget.  the invalid targets could be collected into an object (like target_requester) and sent to the targetPool for removal.  we wont know which property of the pool it came from though (energySupply, energyStorage?)

**Comment by bluecereal** [comment]
Could you explain what prep is again?

**Comment by bluecereal** [comment]
Any chance we could merge targetPool2 in its current state?  I want to test config3 and can't get there with the current targetPool.  prep, drain, and target validation are features in themselves, so creating a new branch to implement them might make more sense anyway.

**Comment by yeliknewo** [comment]
just branch targetPool2 and work off that. prep is higher priority storage

**Comment by yeliknewo** [comment]
this will fix #2
